import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar";
import { AppSidebar } from "./_components/app-sidebar";
import { AppBreadcrumb } from "./_components/app-breadcrumb";
import { Toaster } from "~/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <main>
          <TRPCReactProvider>
            <SidebarProvider>
              <AppSidebar />
              <main className="flex min-w-0 w-full flex-col gap-8 p-4 overflow-hidden">
                <div className="flex items-center gap-4">
                  <SidebarTrigger />
                  <AppBreadcrumb />
                </div>
                {children}
              </main>
            </SidebarProvider>
          </TRPCReactProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
